name: Pull Request check

on:
  pull_request:
    branches:
      - main

jobs:

  Tests-latest-wildfly:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
      fail-fast: false
    name: Tests on JDK ${{ matrix.java }} - default WildFly profile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Tests
        run: mvn verify -s settings.xml -B -fae -Dmaven.test.redirectTestOutputToFile=true
  Tests-wildfly-27:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: false
    name: Tests on JDK ${{ matrix.java }} - WildFly 27 profile (lowest supported)
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Tests
        run: mvn verify -s settings.xml -B -fae -Dmaven.test.redirectTestOutputToFile=true -Pwildfly27
